#  __/\\\\\\\\\\\\\\\______/\\\\\\\\\_________/\\\\\\\\\\\_____/\\\\\\\\\\\\\___
#   _\///////\\\/////_____/\\\\\\\\\\\\\_____/\\\/////////\\\__\/\\\/////////\\\_
#    _______\/\\\_________/\\\/////////\\\___\//\\\______\///___\/\\\_______\/\\\_
#     _______\/\\\________\/\\\_______\/\\\____\////\\\__________\/\\\\\\\\\\\\\/__
#      _______\/\\\________\/\\\\\\\\\\\\\\\_______\////\\\_______\/\\\/////////____
#       _______\/\\\________\/\\\/////////\\\__________\////\\\____\/\\\_____________
#        _______\/\\\________\/\\\_______\/\\\___/\\\______\//\\\___\/\\\_____________
#         _______\/\\\________\/\\\_______\/\\\__\///\\\\\\\\\\\/____\/\\\_____________
#          _______\///_________\///________\///_____\///////////______\///______________
#
#
# ====================================WELCOME TO TASP====================================
# Because I love you and I think that you should be treated like a person that actually
# knows what he or she is doing, I'm going to go ahead and assume that you've already
# flipped through and skimmed the main configuration file for TASP, or at least that you
# have a general idea about how YAML files work.
# For that reason, I don't have to write a giant preface to this file!! YAY!!
#
# TASPPerms works like just about every other permissions plugin that you've used.  The
# only reason I even bothered to make it is so that a) it comes with the TASP suite, and
# b) I wanted to prove to myself that I am capable of making such a thing.
#
# Let's get started.
#
# ╔═════════════════════════════════════════════════════════════════════════════════════╗
# ║                                 GENERAL CONFIGURATION                               ║
# ╚═════════════════════════════════════════════════════════════════════════════════════╝
# This settings determines whether or not a player's group will show up in chat as a
# prefix on their messages.
use-prefix: true
# This is how the group name will be displayed in chat.  {0} represents the group name,
# {1} represents the player name, and {2} represents the message.
# Default: '<{0}>[{1}] {2}'
prefix-format: '<{0}>[{1}] {2}'
# ╔═════════════════════════════════════════════════════════════════════════════════════╗
# ║                                        GROUPS                                       ║
# ╚═════════════════════════════════════════════════════════════════════════════════════╝
# General format for a group:
#   Name:
#     default: false
#     description: 'Description for the group.'
#     permissions: []
#     inheritance: []
#     displayname: 'DifferentName'
#     color: '&f'
#
# Default: will new players on the server be added to this group?  If more than one group
# has this label, the default will be chosen at random.
#
# Description: Can be found by running "/group desc <name>"
#
# Permissions: a list of permissions (in this format):
# permissions:
#    - permission.subpermission
#    - permission.othersubpermission
#
# Inheritance: a list of groups from which to inherit permissions (in this form):
# inheritance: [Default, Player]
#
# Displayname: The name to be displayed in game, not used in commands.
#
# Color: The color of the group in prefixes
groups:
  Jailed:
    default: false
    description: 'Restricted group for rule-breakers.'
    permissions: []
    inheritance: []
    displayname: 'Jailed'
    color: '&0'
  Default:
    default: true
    description: 'The default group for the server.'
    permissions: []
    inheritance: []
    displayname: 'Default'
    color: '&8'
  Player:
    default: false
    description: 'Slightly elevated group for regulars.'
    permissions: []
    inheritance: []
    displayname: 'Player'
    color: '&2'
  Moderator:
    default: false
    description: 'People who regulate the players.'
    permissions: []
    inheritance: []
    displayname: 'Mod'
    color: '&6'
  Administrator:
    default: false
    description: 'Those who are given almost-omnipotency over the server.'
    permissions: []
    inheritance: []
    displayname: 'Admin'
    color: '&4'
  Owner:
    default: false
    description: 'Simply put: gods.'
    permissions: []
    inheritance: []
    displayname: 'Owner'
    color: '&1'